
- testcase:
      name: ni_mpls_tunn_config_admin_status
      id: 1
      description: >
          This test is to set type of the interface.
      rpcs:
          - template: ni_mpls_tunn_config_admin_status.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   interface_name: "1"
                   type: "ethernet3Mbit"

- testcase:
      name: ni_mpls_tunn_config_description
      id: 2
      description: >
          This test is to define the mtu parameter.
      rpcs:
          - template: ni_mpls_tunn_config_description.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   interface_name: "1"
                   mtu: "1450"

- testcase:
      name: ni_mpls_tunn_config_hold_priority
      id: 3
      description: >
          This test is to set description on the interface.
      rpcs:
          - template: ni_mpls_tunn_config_hold_priority.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   interface_name: "1"
                   description: "Test if_config_description 2"

- testcase:
      name: ni_mpls_tunn_config_metric
      id: 4
      description: >
          This test is to enabled the interface.
      rpcs:
          - template: ni_mpls_tunn_config_metric.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   interface_name: "1"
                   enabled: "false"

- testcase:
      name: ni_mpls_tunn_config_metric_type
      id: 5
      description: >
          This test is to define the tag protocol on the VLAN.
      rpcs:
          - template: ni_mpls_tunn_config_metric_type.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                   interface_name: "1"
                   tpid: "TPID_0X9200"

- testcase:
      name: ni_mpls_tunn_config_name
      id: 6
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_name.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_preference
      id: 7
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_preference.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_protection_style_requested
      id: 8
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_protection_style_requested.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_reoptimize_timer
      id: 9
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_reoptimize_timer.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_setup_priority
      id: 10
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_setup_priority.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_signaling_protocol
      id: 11
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_signaling_protocol.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_soft_preemption
      id: 12
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_soft_preemption.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_source
      id: 13
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_source.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"

- testcase:
      name: ni_mpls_tunn_config_type
      id: 14
      description: >
          This test is defined to enable an interface
          loopback mode.
      rpcs:
          - template: ni_mpls_tunn_config_type.xml
            target: candidate
            operation: edit-config
            commit: true
            params:
                  interface_name: "Loopback0"
                  type: "softwareLoopback"
                  loopback_mode: "true"                 